version: '3.8'

services:
  backend:
    build: ./backend          # Path to backend Dockerfile
    ports:
      - "5000:5000"           # Expose backend port
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://postgres:mypassword@db/tododb  # Add this line
    depends_on:
      - db

  frontend:
    build: ./frontend         # Path to frontend Dockerfile
    ports:
      - "3000:80"             # Map host port 3000 → container port 80 (Nginx)
    depends_on:
      - backend              # Ensure backend starts first

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tododb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Optional: expose DB port for external tools

volumes:
    postgres_data:  # ← This defines the volume properly