replicaCount: 2
image:
  repository: faresbadocker/todo-frontend
  tag: 1.0.0
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: frontend.example.com

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  apiUrl: ""

