apiVersion: v1
kind: Service
metadata:
  name: backend  # Make sure this is exactly "backend"
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http